### ISSUE TITLE
Detail and implement API schema

### ISSUE THREAD

**Issue by ccarterlandis** [computationalmystic/augur-group13#3]
Fully detailing our proposed API schema before we implement it will help us make sure that the organizational choices we make will make sense for our use cases.

Refinement:
We will continue to discuss and refine our API schema as development continues. Adding further comments in the API and publishing the schema on our github page are short term goals. Once the schema is fully implemented, an accurate and "finalized" version should be uploaded for future reference.

**Comment by Luke-Fisher** [comment]
Here's a summary of my progress on the issue from Thursday and Friday:

Thursday: It immediately became clear how closely tied this issue is to the work on the server when I looked at the amazing @ccarterlandis 's code. I spent the bulk of time on this issue trying to understand how his code worked together and how best to adapt it and add on to it for our project. I liked the authentic experience of reading, understanding, and working off of of someone else's code. 

Friday: Similarly to my work on the flask server, nothing's really working together. The API wasn't hitting any of its endpoints and I couldn't figure out why (I considered creating a new issue for this, but it seemed a bit too minor to warrant one). The server issues made working on this issue significantly more difficult. Most of my time was spent trying to understand how routing works and what I was doing wrong.
