### ISSUE TITLE
Hook UI up to DoSOCSv2 plugin

### ISSUE THREAD

**Issue by ccarterlandis** [computationalmystic/augur-group13#5]
**Type:** Structural

**Purpose:** 
Once the Augur plugin for accessing the DoSOCSv2 wrapper api (#4) is completed. Hook up the different information endpoints to the @Pauldg7 's UI design. [https://github.com/computationalmystic/augur-group13/blob/master/sprint2/AugurUI.png](UI.)

**Step in overall process (Bold item is the item this issue aims to solve):** 
1. Request git URL through Augur
2. Augur DoSOCSv2 plugin requests DoSOCS information from the DoSOCSv2 Wrapper Flask Server (#2)
3. **Augur DoSOCSv2 plugin takes returned information and parses it into the two UI enum fields (Shown above, Described below)**

**Different UI Enum States:**
Redistribution (Double Enum Field) - Approved (Redistribution Allowed) or Rejected (Redistribution Forbidden), Requires Author Recognition (This is optional, as this is only for the case when redistribution is allowed, but only under this one condition). 

Software Warranty - Warranty (Open Source code that has a warranty with it) No Warranty (Code is distributed to be used "as is" with no guarantee it won't fail.

**Progress Update: (5/12/19)**
Delayed due to issue #4 not being completed.

**Comment by calebheinzman** [comment]
I would suggest making issues less convoluted. It is kind of a pain to click through each issue link to understand what you are talking about. I would recommend providing full details in the original post. I would also recommend explaining the issue from the beginning. Stating that "we'll need to hook it up to the UI" and then explaining it in the "Refinement" section is a little bit confusing. My eyes are having to look everywhere for information. It would be nice to just read from the beginning so that I can easily understand it.
